/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import {
  Message,
} from './models/message-model';

declare global {

  namespace StencilComponents {
    interface ChatBob {
      'callback': (message: Message) => void;
      'getMessages': () => Message[];
      'name': string;
      'scrollToBottom': () => void;
    }
  }

  interface HTMLChatBobElement extends StencilComponents.ChatBob, HTMLStencilElement {}

  var HTMLChatBobElement: {
    prototype: HTMLChatBobElement;
    new (): HTMLChatBobElement;
  };
  interface HTMLElementTagNameMap {
    'chat-bob': HTMLChatBobElement;
  }
  interface ElementTagNameMap {
    'chat-bob': HTMLChatBobElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'chat-bob': JSXElements.ChatBobAttributes;
    }
  }
  namespace JSXElements {
    export interface ChatBobAttributes extends HTMLAttributes {
      'callback'?: (message: Message) => void;
      'name'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
